//// <auto-generated />
//using System;
//using Cargo.Models;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace Cargo.Migrations
//{
//    [DbContext(typeof(CargoContext))]
//    [Migration("20231127170837_Initial")]
//    partial class Initial
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.12")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Cargo.Models.Car", b =>
//                {
//                    b.Property<int>("CarId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

//                    b.Property<int>("BodyVolume")
//                        .HasColumnType("int");

//                    b.Property<int?>("CarBrandId")
//                        .HasColumnType("int");

//                    b.Property<int>("LiftingCapacity")
//                        .HasColumnType("int");

//                    b.Property<string>("RegistrationNumber")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("CarId");

//                    b.HasIndex("CarBrandId");

//                    b.ToTable("Cars");
//                });

//            modelBuilder.Entity("Cargo.Models.CarBrand", b =>
//                {
//                    b.Property<int>("CarBrandId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarBrandId"));

//                    b.Property<string>("BrandName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("CarBrandId");

//                    b.ToTable("CarBrands");
//                });

//            modelBuilder.Entity("Cargo.Models.CargoTransportation", b =>
//                {
//                    b.Property<int>("DocumentId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

//                    b.Property<int?>("CarId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("Date")
//                        .HasColumnType("datetime2");

//                    b.Property<int?>("DistanceId")
//                        .HasColumnType("int");

//                    b.Property<int?>("DriverId")
//                        .HasColumnType("int");

//                    b.Property<int?>("LoadId")
//                        .HasColumnType("int");

//                    b.Property<int?>("OrganizationId")
//                        .HasColumnType("int");

//                    b.Property<int?>("TransportationTariffId")
//                        .HasColumnType("int");

//                    b.HasKey("DocumentId");

//                    b.HasIndex("CarId");

//                    b.HasIndex("DistanceId");

//                    b.HasIndex("DriverId");

//                    b.HasIndex("LoadId");

//                    b.HasIndex("OrganizationId");

//                    b.HasIndex("TransportationTariffId");

//                    b.ToTable("CargoTransportations");
//                });

//            modelBuilder.Entity("Cargo.Models.Distance", b =>
//                {
//                    b.Property<int>("DistanceId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistanceId"));

//                    b.Property<int?>("ArrivalSettlementId")
//                        .HasColumnType("int");

//                    b.Property<int?>("DeparturesSettlementId")
//                        .HasColumnType("int");

//                    b.Property<int?>("Distance1")
//                        .HasColumnType("int");

//                    b.HasKey("DistanceId");

//                    b.HasIndex("ArrivalSettlementId");

//                    b.HasIndex("DeparturesSettlementId");

//                    b.ToTable("Distances");
//                });

//            modelBuilder.Entity("Cargo.Models.Driver", b =>
//                {
//                    b.Property<int>("DriverId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

//                    b.Property<string>("FullName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PassportDetails")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("DriverId");

//                    b.ToTable("Drivers");
//                });

//            modelBuilder.Entity("Cargo.Models.Load", b =>
//                {
//                    b.Property<int>("LoadId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoadId"));

//                    b.Property<string>("LoadName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Volume")
//                        .HasColumnType("int");

//                    b.Property<int>("Weight")
//                        .HasColumnType("int");

//                    b.HasKey("LoadId");

//                    b.ToTable("Loads");
//                });

//            modelBuilder.Entity("Cargo.Models.Organization", b =>
//                {
//                    b.Property<int>("OrganizationId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationId"));

//                    b.Property<string>("OrganizationName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("OrganizationId");

//                    b.ToTable("Organizations");
//                });

//            modelBuilder.Entity("Cargo.Models.Settlement", b =>
//                {
//                    b.Property<int>("SettlementId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettlementId"));

//                    b.Property<string>("SettlementName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("SettlementId");

//                    b.ToTable("Settlements");
//                });

//            modelBuilder.Entity("Cargo.Models.TransportationTariff", b =>
//                {
//                    b.Property<int>("TransportationTariffId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransportationTariffId"));

//                    b.Property<int>("TariffPerM3Km")
//                        .HasColumnType("int");

//                    b.Property<int>("TariffPerTKm")
//                        .HasColumnType("int");

//                    b.HasKey("TransportationTariffId");

//                    b.ToTable("TransportationTariffs");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedName")
//                        .IsUnique()
//                        .HasDatabaseName("RoleNameIndex")
//                        .HasFilter("[NormalizedName] IS NOT NULL");

//                    b.ToTable("AspNetRoles", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("RoleId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetRoleClaims", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<int>("AccessFailedCount")
//                        .HasColumnType("int");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<bool>("EmailConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<bool>("LockoutEnabled")
//                        .HasColumnType("bit");

//                    b.Property<DateTimeOffset?>("LockoutEnd")
//                        .HasColumnType("datetimeoffset");

//                    b.Property<string>("NormalizedEmail")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedUserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("PasswordHash")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("PhoneNumberConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("SecurityStamp")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("TwoFactorEnabled")
//                        .HasColumnType("bit");

//                    b.Property<string>("UserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedEmail")
//                        .HasDatabaseName("EmailIndex");

//                    b.HasIndex("NormalizedUserName")
//                        .IsUnique()
//                        .HasDatabaseName("UserNameIndex")
//                        .HasFilter("[NormalizedUserName] IS NOT NULL");

//                    b.ToTable("AspNetUsers", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserClaims", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderKey")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderDisplayName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("LoginProvider", "ProviderKey");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserLogins", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("RoleId")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("UserId", "RoleId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetUserRoles", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Value")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("UserId", "LoginProvider", "Name");

//                    b.ToTable("AspNetUserTokens", (string)null);
//                });

//            modelBuilder.Entity("Cargo.Models.Car", b =>
//                {
//                    b.HasOne("Cargo.Models.CarBrand", "CarBrand")
//                        .WithMany("Cars")
//                        .HasForeignKey("CarBrandId");

//                    b.Navigation("CarBrand");
//                });

//            modelBuilder.Entity("Cargo.Models.CargoTransportation", b =>
//                {
//                    b.HasOne("Cargo.Models.Car", "Car")
//                        .WithMany("CargoTransportations")
//                        .HasForeignKey("CarId");

//                    b.HasOne("Cargo.Models.Distance", "Distance")
//                        .WithMany("CargoTransportations")
//                        .HasForeignKey("DistanceId");

//                    b.HasOne("Cargo.Models.Driver", "Driver")
//                        .WithMany("CargoTransportations")
//                        .HasForeignKey("DriverId");

//                    b.HasOne("Cargo.Models.Load", "Load")
//                        .WithMany("CargoTransportations")
//                        .HasForeignKey("LoadId");

//                    b.HasOne("Cargo.Models.Organization", "Organization")
//                        .WithMany("CargoTransportations")
//                        .HasForeignKey("OrganizationId");

//                    b.HasOne("Cargo.Models.TransportationTariff", "TransportationTariff")
//                        .WithMany("CargoTransportations")
//                        .HasForeignKey("TransportationTariffId");

//                    b.Navigation("Car");

//                    b.Navigation("Distance");

//                    b.Navigation("Driver");

//                    b.Navigation("Load");

//                    b.Navigation("Organization");

//                    b.Navigation("TransportationTariff");
//                });

//            modelBuilder.Entity("Cargo.Models.Distance", b =>
//                {
//                    b.HasOne("Cargo.Models.Settlement", "ArrivalSettlement")
//                        .WithMany("DistanceArrivalSettlements")
//                        .HasForeignKey("ArrivalSettlementId");

//                    b.HasOne("Cargo.Models.Settlement", "DeparturesSettlement")
//                        .WithMany("DistanceDeparturesSettlements")
//                        .HasForeignKey("DeparturesSettlementId");

//                    b.Navigation("ArrivalSettlement");

//                    b.Navigation("DeparturesSettlement");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Cargo.Models.Car", b =>
//                {
//                    b.Navigation("CargoTransportations");
//                });

//            modelBuilder.Entity("Cargo.Models.CarBrand", b =>
//                {
//                    b.Navigation("Cars");
//                });

//            modelBuilder.Entity("Cargo.Models.Distance", b =>
//                {
//                    b.Navigation("CargoTransportations");
//                });

//            modelBuilder.Entity("Cargo.Models.Driver", b =>
//                {
//                    b.Navigation("CargoTransportations");
//                });

//            modelBuilder.Entity("Cargo.Models.Load", b =>
//                {
//                    b.Navigation("CargoTransportations");
//                });

//            modelBuilder.Entity("Cargo.Models.Organization", b =>
//                {
//                    b.Navigation("CargoTransportations");
//                });

//            modelBuilder.Entity("Cargo.Models.Settlement", b =>
//                {
//                    b.Navigation("DistanceArrivalSettlements");

//                    b.Navigation("DistanceDeparturesSettlements");
//                });

//            modelBuilder.Entity("Cargo.Models.TransportationTariff", b =>
//                {
//                    b.Navigation("CargoTransportations");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
